In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("phishing_site_urls.csv")

In [3]:
# df = data.sample(n=50000, random_state=42)

In [4]:
df.shape

(549346, 2)

In [5]:

df['Label'].value_counts()

Label
good    392924
bad     156422
Name: count, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Label'] = le.fit_transform(df['Label'])

In [7]:
df.head(10)

                                                 URL  Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...      0
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...      0
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....      0
3  mail.printakid.com/www.online.americanexpress....      0
4  thewhiskeydregs.com/wp-content/themes/widescre...      0
5               smilesvoegol.servebbs.org/voegol.php      0
6  premierpaymentprocessing.com/includes/boleto-2...      0
7  myxxxcollection.com/v1/js/jih321/bpd.com.do/do...      0
8                                super1000.info/docs      0
9  horizonsgallery.com/js/bin/ssl1/_id/www.paypal...      0

In [8]:
df["url_len"]=df["URL"].str.len()

In [9]:
df['at_symbol'] = df['URL'].str.contains('@').astype(int)

In [10]:
df['hyphen_count'] = df['URL'].str.count('-')
df['question_mark_count'] = df['URL'].str.count('\?')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549346 entries, 0 to 549345
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   URL                  549346 non-null  object
 1   Label                549346 non-null  int64
 2   url_len              549346 non-null  int64
 3   at_symbol            549346 non-null  int64
 4   hyphen_count         549346 non-null  int64
 5   question_mark_count  549346 non-null  int64
dtypes: int64(5), object(1)
memory usage: 25.1+ MB

In [12]:

X = df.drop(['URL', 'Label'], axis=1)


y = df['Label']

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

y_train.shape

(439476,)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.22      0.35     31200
           1       0.76      0.97      0.85     78670

    accuracy                           0.76    109870
   macro avg       0.77      0.60      0.60    109870
weighted avg       0.77      0.76      0.71    109870

In [15]:
df["dots_counts"]=df["URL"].str.count("\.")

In [16]:
suspicious_words = 'login|update|secure|verify|free|admin'
df['has_suspicious_words'] = df['URL'].str.contains(suspicious_words, case=False).astype(int)

In [17]:
ip_pattern = r'(([01]?\d\d?|2[0-4]\d|25[0-5])\.){3}([01]?\d\d?|2[0-4]\d|25[0-5])'
df['has_ip'] = df['URL'].str.contains(ip_pattern).astype(int)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17840\1427959527.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['has_ip'] = df['URL'].str.contains(ip_pattern).astype(int)

In [18]:
df.head(30)

,URL,Label,url_len,at_symbol,hyphen_count,question_mark_count,dots_counts,has_suspicious_words,has_ip
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,0,225,0,4,1,6,1,0
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,0,81,0,2,0,5,0,0
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,0,177,0,1,0,7,1,0
3,mail.printakid.com/www.online.americanexpress....,0,60,0,0,0,6,0,0
4,thewhiskeydregs.com/wp-content/themes/widescre...,0,116,0,1,1,1,0,0
5,smilesvoegol.servebbs.org/voegol.php,0,36,0,0,0,3,0,0
6,premierpaymentprocessing.com/includes/boleto-2...,0,61,0,3,0,2,0,0
7,myxxxcollection.com/v1/js/jih321/bpd.com.do/do...,0,60,0,0,0,5,0,0
8,super1000.info/docs,0,19,0,0,0,1,0,0
9,horizonsgallery.com/js/bin/ssl1/_id/www.paypal...,0,193,0,3,1,4,1,0
10,phlebolog.com.ua/libraries/joomla/results.php,0,45,0,0,0,3,0,0
11,docs.google.com/spreadsheet/viewform?formkey=d...,0,79,0,0,1,2,0,0
12,www.coincoele.com.br/Scripts/smiles/?pt-br/Pag...,0,63,0,1,1,4,0,0
13,www.henkdeinumboomkwekerij.nl/language/pdf_fon...,0,59,0,0,0,3,0,0
14,perfectsolutionofall.net/wp-content/themes/twe...,0,64,0,1,0,1,0,0
15,lingshc.com/old_aol.1.3/?Login=&amp;Lis=10&amp...,0,72,0,0,1,3,1,0
16,anonymeidentity.net/remax./remax.htm,0,36,0,0,0,3,0,0
17,dutchweb.gtphost.com/zimbra/exch/owa/uleth/ind...,0,53,0,0,0,3,0,0
18,www.avedeoiro.com/site/plugins/chase/,0,37,0,0,0,2,0,0
19,asladconcentration.com/paplkuk1/webscrcmd=_hom...,0,63,0,1,0,1,0,0
20,www.regaranch.info/grafika/file/2012/atualizac...,0,65,0,0,0,5,0,0
21,optimistic-pessimism.com/aoluserupdatealert.in...,0,52,0,1,0,3,1,0
22,mercadolivre.com.br.premiosfidelidade2012.com....,0,59,0,0,0,5,0,0
23,www.everythinggoingon.net/~gpeveryt/home/Email/,0,47,0,0,0,2,0,0
24,mercadolivre.com.br.premiosfidelidade2012.com.br/,0,49,0,0,0,5,0,0
25,www.revitolcream.org/wp-content/plugins/all-in...,0,87,0,6,0,2,1,0
26,jameshowardmusic.com/wp-content/themes/widescr...,0,77,0,1,0,2,0,0
27,xini.eu/00Qe,0,12,0,0,0,1,0,0
28,myxxxcollection.com/v1/js/555klisdr/bpd.com.do...,0,63,0,0,0,5,0,0
29,paypal.com.cgi.bin.webscr.cmd.login.submit.dis...,0,135,0,1,0,11,1,0

In [19]:
X = df.drop(['URL', 'Label'], axis=1)
y = df['Label']

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

print(f"new accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%\n")
print(classification_report(y_test, y_pred))

new accuracy: 80.47%

              precision    recall  f1-score   support

           0       0.84      0.38      0.53     31200
           1       0.80      0.97      0.88     78670

    accuracy                           0.80    109870
   macro avg       0.82      0.68      0.70    109870
weighted avg       0.81      0.80      0.78    109870

In [21]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

print(f"New Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%\n")
print(classification_report(y_test, y_pred))

New Accuracy: 73.74%

              precision    recall  f1-score   support

           0       0.53      0.65      0.58     31200
           1       0.85      0.77      0.81     78670

    accuracy                           0.74    109870
   macro avg       0.69      0.71      0.70    109870
weighted avg       0.76      0.74      0.74    109870

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_tfidf = tfidf.fit_transform(df['URL'])

y = df['Label']

X_tfidf.shape

(549346, 528563)

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


X_train_tf, X_test_tf, y_train_tf, y_test_tf = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)
log_model = LogisticRegression(class_weight='balanced', max_iter=1000)
log_model.fit(X_train_tf, y_train_tf)
y_pred_tf = log_model.predict(X_test_tf)
print(f"\n NLP MODEL ACCURACY: {accuracy_score(y_test_tf, y_pred_tf) * 100:.2f}%\n")
print(classification_report(y_test_tf, y_pred_tf))

 NLP MODEL ACCURACY: 96.43%

              precision    recall  f1-score   support

           0       0.94      0.94      0.94     31200
           1       0.97      0.98      0.98     78670

    accuracy                           0.96    109870
   macro avg       0.96      0.96      0.96    109870
weighted avg       0.96      0.96      0.96    109870

In [25]:
import pickle

with open('phishing_model.pkl', 'wb') as file:
    pickle.dump(log_model, file)
with open('tfidf_vectorizer.pkl', 'wb') as file:
    pickle.dump(tfidf, file)